### ISSUE TITLE
COPYING states GPLv3 but files are LGPLv2

### ISSUE THREAD

**Issue by blino** [asrashley/gst-cencdec#1]
The COPYING file states that the project is GPLv3, but all source code files are licensed under LGPLv2.
Also, the rpm spec files lists a commercial license.
What is the real license of this project?
Thanks

**Comment by asrashley** [comment]
Thank you for spotting that error. It has been released under the same licensing as GStreamer, using LGPL v2

**Comment by blino** [comment]
Thanks for the update!

**Comment by ocrete** [comment]
Actually, the COPYING file is still the wrong one, it's the GPLv2 instead of the LGPL. Here is the one you really mean I think:
https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
